[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=/NODEFAULTLIB:MSVCRT"]
[target.'cfg(target_os="macos")']
rustflags = [
    "-C", "link-args=-sectcreate __CGPreLoginApp __cgpreloginapp /dev/null",
]
[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-args=-mios-version-min=13.0",
]
#[target.'cfg(target_os="linux")']
# glibc-static required, this may fix https://github.com/rustdesk/rustdesk/issues/9103, but I do not want this big change
# this is unlikely to help also, because the other so files still use libc dynamically
#rustflags = [
#    "-C", "link-args=-Wl,-Bstatic -lc -Wl,-Bdynamic"
#]
[net]
git-fetch-with-cli = true

# ShopRemote 빌드 환경변수 - cargo build 직접 실행 시에도 서버키와 주소가 자동 주입됨
[env]
RS_PUB_KEY = "r8Mxm2lf9f5l9MGHufGp7aPiMEHcygeCPhcdps30b5w="
RENDEZVOUS_SERVER = "ai.ilv.co.kr"
